name: Deploy para VM Azure

on:
  push:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login no Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Garantir que a VM esteja ligada
      run: |
        az vm start --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_VM_NAME }}

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build da imagem
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/projeto_so:latest .

    - name: Push para Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/projeto_so:latest

    - name: Deploy na VM via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/projeto_so:latest
          docker stop servidor_so || true
          docker rm servidor_so || true
          docker run -d --name servidor_so -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/projeto_so:latest
